### ISSUE TITLE
Imprimir partes de Zowi

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/zowi#3]
Necesitamos ir imprimiendo piezas de zowi.

Este mensaje lo iré manteniendo yo con ediciones. Última edición 15 de mayo 19:33.

Se debe avisar cuando alguien vaya a imprimir una pieza con un comentario, para evitar que hagamos piezas de más. Revisar los últimos comentarios antes de empezar a imprimir.

Cada nueva pieza impresa correctamente debe ser avisada con un comentario que incluya:

- Qué se ha impreso (nombre de la pieza o piezas) y cantidad.
- Material.
- Color.
- Foto (opcional).

Se recomienda a los que colaboren que impriman las piezas simétricas (como pies, piernas, hombros y brazos) por parejas, para poder guardar cierta estética a la hora de construir los robots.

Piezas que se necesitan imprimir:

| Nombre de la pieza | Link stl | Objetivo de piezas | Piezas que llevamos | Piezas que faltan |
|---|---|---|---|---|
| Pie izquierdo | https://github.com/asrob-uc3m/zowi/blob/master/mods/Zowimanoid/parts/stl/leftFoot.stl | 6 | 6 | 0 |
| Pie derecho | https://github.com/asrob-uc3m/zowi/blob/master/mods/Zowimanoid/parts/stl/rightFoot.stl | 6 | 6  | 0 |
| Pierna izquierda | https://github.com/asrob-uc3m/zowi/blob/master/mods/Zowimanoid/parts/stl/LeftLeg_more_holes.stl | 6 | 6 | 0 |
| Pierna derecha| https://github.com/asrob-uc3m/zowi/blob/master/mods/Zowimanoid/parts/stl/RightLeg_more_holes.stl | 6 | 6 | 0 |
| Chassis | https://github.com/asrob-uc3m/zowi/blob/master/mods/Zowimanoid/parts/stl/chassis_nano_sensor_shield.stl | 6 | 6 | 0 |

**Para descargar** las piezas se puede pinchar el botón Download. Si no aparece este botón, con click derecho en Raw y pulsar en "guardar enlace como" también se iniciará la descarga.

Se irán añadiendo nuevas piezas a la lista conforme estén validadas.

Menciono a @David-Estevez @JavierIH @jorgercobo @JorFru @andrespy @luciahonrubia para suscribirlos al hilo

**Comment by Siotma** [comment]
Inicialmente he tenido en cuenta las siguientes piezas:

Pies izquierdos:

- 1 de Hija Resurrection ABSVerde
- 1 de Blacky ABS Amarillo
- 1 de Siotma PLA Rojo

Pies derechos:

- 1 de Hija Resurrection ABS Verde
- 1 de Blacky ABS Amarillo
- 1 de Siotma PLA Rojo

Piernas izquierdas:

- 1 de Siotma PLA Rojo

Piernas derechas:

- 1 de Siotma PLA Rojo

**Comment by David-Estevez** [comment]
Yo voy a poner a imprimir **una pieza de cada tipo**, en PLA morado

Edit: primer intento, fracaso absoluto. Me encontré las piezas así al llegar a casa:
![img_20170423_002348](https://cloud.githubusercontent.com/assets/1451819/25313125/a07b99ca-2828-11e7-8cea-46e69508032b.jpg)

Vuelvo a intentarlo en breves.

**Comment by David-Estevez** [comment]
Confirmo que he impreso las siguientes piezas con éxito en PLA morado:

* 1x Pie izquierdo
* 1x Pie derecho
* 1x Pierna izquierda
* 1x Pierna derecha

**Comment by Siotma** [comment]
Actualizado!

**Comment by JavierIH** [comment]
Aporto un par de pies (izquierdo y derecho) de PLA amarillo.

**Comment by Siotma** [comment]
Gracias Javi! Tráelos la próxima vez que te veamos.

Actualizado!

**Comment by JorFru** [comment]
Dos priernas en negro.
Puede ser hasta ahora la mayor calidad de imprusación que he conseguido. Obra de Hija Reurrection con el perfil de Slic3r JorFru-test
![photo_2017-04-24_19-47-26](https://cloud.githubusercontent.com/assets/11017088/25350862/dbac1f8e-2926-11e7-9345-222f3401ed2b.jpg)

**Comment by Siotma** [comment]
Actualizado! Gracias @JorFru

**Comment by Siotma** [comment]
Nueva pieza añadida: chassis (https://github.com/asrob-uc3m/zowi/blob/master/mods/Zowimanoid/parts/stl/chassis_nano_sensor_shield.stl)

![chassis_nano_sensor_shield](https://cloud.githubusercontent.com/assets/6171234/25397901/46293d7e-29ea-11e7-8680-81d078483b82.PNG)

He hecho una en PLA negro.

**Comment by Siotma** [comment]
He impreso una pierna de cada en PLA azul.

![piernas pla azul](https://cloud.githubusercontent.com/assets/6171234/25557229/d4d26566-2d0d-11e7-96e1-be4d00f80fb7.PNG)

Actualizo.

**Comment by Siotma** [comment]
Subo este hilo para comunicar que es **urgente** imprimir [piezas de chassis](https://github.com/asrob-uc3m/zowi/blob/master/mods/Zowimanoid/parts/stl/chassis_nano_sensor_shield.stl).

Por favor, quien pueda que intente sacar alguno antes del domingo.

**Comment by Siotma** [comment]
Hoy, he impreso un chassis en PLA rojo.

Me dispongo a imprimir otro más en PLA amarillo.

**Comment by David-Estevez** [comment]
Yo estoy imprimiendo uno en PLA morado, os aviso cuando esté completo.

**Comment by David-Estevez** [comment]
Confirmo que tengo un chasis en PLA morado.

**Comment by Siotma** [comment]
Finalmente, imprimí el Chassis en PLA amarillo y un par de pies en PLA negro.

Actualizo.

**Comment by Siotma** [comment]
A la vista del poco movimiento, hoy he impreso otro chasis en PLA azul.

URGE IMPRIMIR las piezas que faltan ya que se necesitan para mañana.

**Comment by Siotma** [comment]
He tenido un rato para sacar una pierna derecha en PLA amarillo.

Faltaría una pierna izquierda para tener 5 robots completos.

**Comment by David-Estevez** [comment]
Acordáos de postear por aquí la pieza que váis a imprimir para reservarla, que si no puede ser que imprimamos dos veces la misma.... :sweat_smile:

**Comment by Siotma** [comment]
Toda la razón David, perdón por no haberlo hecho que tenía el tiempo justo para comer y pirarme otra vez 😅

**Comment by David-Estevez** [comment]
No te preocupes, sólo era un "kindly reminder" :smile:

**Comment by jorgercobo** [comment]
Imprimiendo un Leftleg en Blacky y un chassis en Hija Resurrection [Actualizado]

**Comment by jorgercobo** [comment]
Leftleg y chassis imprimidos.

![photo_2017-05-09_18-40-18](https://cloud.githubusercontent.com/assets/9537923/25862079/0e7075b6-34e7-11e7-8284-866d236130e4.jpg)
![photo_2017-05-09_18-40-21](https://cloud.githubusercontent.com/assets/9537923/25862080/0e8f63fe-34e7-11e7-9a7d-6b75fa3cf3bf.jpg)

Imprimiendo Rightleg en Blacky [EDIT: Cancelada por fallo en la impresora 😞  ]

**Comment by Siotma** [comment]
Voy a imprimir la pierna izquierda correspondiente con la derecha que imprimí ayer.

Ya solo faltaría una pierna derecha de Blacky para tenerlo todo :')

**Comment by Siotma** [comment]
Pierna izquierda en PLA amarillo ✔️

**Comment by JorFru** [comment]
Habemus pierna derecha.
El problema es que no es de Blacky, es BLACK.
A secas, obra de Hija.
Está en la caja de Zowimanoides

**Comment by tocalvo** [comment]
Buenas! Qué piezas faltan por imprimir? Y las intento traer todas el miércoles.

**Comment by Siotma** [comment]
Gracias por tu impresión JorFru. Las piezas de esta Issue ya están todas impresas.

@tocalvo , muchas gracias por ofrecerte para imprimir piezas. Como he dicho, las que corresponden a esta issue, que son todas genéricas, ya están impresas. Sin embargo, ahora vendrá la parte de imprimir las piezas personalizadas ( #5 ), tarea en la que tu colaboración sería muy valiosa.

Cierro
