### ISSUE TITLE
Tabla de zowimanoides rota

### ISSUE THREAD

**Issue by JavierIH** [asrob-uc3m/zowi#4]
Solía haber una tabla que listaba todos los zowimanoides y sus creadores. Por alguna razón la tabla se ha roto (por algún error de formato en el markdown, supongo).

https://github.com/asrob-uc3m/zowi/blob/master/mods/README.md

¿Alguna idea?

**Comment by Siotma** [comment]
El error era una celda extra en las líneas que definen el número de columnas.
Esto había:
`| ------------- | ------------- | ------------- | ------------- |`
Esto debe haber:
`| ------------- | ------------- | ------------- |`

Ya está arreglado en 0621a112bb3920b95ee60b7987989f88ad7cbba5.

**Comment by JavierIH** [comment]
Gracias @Siotma! :beer:
