### ISSUE TITLE
Llevarme Zowi a casa

### ISSUE THREAD

**Issue by VentressAsajj** [asrob-uc3m/zowi#6]
Hola a todos:
He pensado aprovechar esta semana santa para intentar terminar uno de los zowis que tenemos en la asociación. Os importa que me lleve uno a casa? hay uno que necesita calibrase y cargarle el programa.

**Comment by Siotma** [comment]
Hola.
Yo creo que es factible. Para oficializarlo te pediría:
1. Foto y breve descripción del estado del robot en el momento en que te lo llevas.
2. Lista de modificaciones que planeas realizar sobre el robot. Debes demostrar que tras realizar este proceso, el robot pasará a estar en un mejor estado del que se encuentra actualmente.
3. El día que lo devuelvas. Otra foto y otra descripción de las diferencias de estado del robot con respecto al día que te lo llevaste.

Que lo disfrutes :)

**Comment by David-Estevez** [comment]
El repositorio de cosas a nivel de asociación es el de actas. Para encontrar más fácilmente la issue, la he movido a https://github.com/asrob-uc3m/actas/issues/133
